#!/usr/bin/env bash

set -e

echo "==== vim/install: start"

if [ ! -e ~/.vim ]; then
  git clone https://github.com/cedarcode/cedarvim ~/.vim
fi

cd ~/.vim
git submodule init
git submodule update
cd -

echo "==== vim/install: finished"
